# **Deep learning practical assignment 3**

# Installing and importing packages

In [1]:
!pip install matplotlib==3.2.2 numpy==1.19.5 scikit-learn==0.22.2.post1 keras==2.7.0 tensorflow==2.7.0

     |████████████████████████████████| 7.1 MB 3.6 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.1
    Uninstalling scikit-learn-1.0.1:
      Successfully uninstalled scikit-learn-1.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.22.2.post1 which is incompatible.


In [2]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from sklearn.datasets import fetch_olivetti_faces
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, models 
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D , Flatten, AveragePooling2D
from keras.preprocessing import image
from sklearn.preprocessing import OneHotEncoder

# 1.Implementing CNN architecture

In [3]:
def lenet_5_model(dataset, x, y, n_outputs):
  
  # Split the data for training and testing
  train_x, val_x, train_y, val_y = train_test_split(x, y, test_size=0.20)
  train_x, test_x, train_y, test_y = train_test_split(train_x, train_y, test_size=0.20)

  #define letnet5
  lenet_5_model = Sequential()
  lenet_5_model.add(Conv2D(6, kernel_size=5, strides=1,  activation='tanh', input_shape=train_x[0].shape, padding='same'))
  lenet_5_model.add(AveragePooling2D())
  lenet_5_model.add(Conv2D(16, kernel_size=5, strides=1, activation='tanh', padding='same'))
  lenet_5_model.add(AveragePooling2D())
  lenet_5_model.add(Flatten())
  lenet_5_model.add(Dense(120, activation='tanh'))
  lenet_5_model.add(Dense(84, activation='tanh'))
  lenet_5_model.add(Dense(n_outputs, activation='softmax'))

  print(lenet_5_model.summary())
  lenet_5_model.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['accuracy', 'Recall', 'Precision'])
  lenet_5_model.fit(train_x, train_y, epochs=30, validation_data=(val_x, val_y))
  lenet_5_model.evaluate(test_x, test_y)



In [4]:
def vgg_16_model(dataset, x, y, n_outputs):

  # Split the data for training and testing
  train_x, val_x, train_y, val_y = train_test_split(x, y, test_size=0.20)
  train_x, test_x, train_y, test_y = train_test_split(train_x, train_y, test_size=0.20)

  vgg_16_model = Sequential()
  vgg_16_model.add(Conv2D(input_shape=train_x[0].shape ,filters=64,kernel_size=(3,3),padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
  vgg_16_model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
  vgg_16_model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
  vgg_16_model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
  vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
  vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
  if (dataset == 'olivetti'):
    vgg_16_model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
    vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
    vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
    vgg_16_model.add(Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"))
    vgg_16_model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))
  vgg_16_model.add(Flatten())
  vgg_16_model.add(Dense(units=4096,activation="relu"))
  vgg_16_model.add(Dense(units=4096,activation="relu"))
  vgg_16_model.add(Dense(units=n_outputs, activation="softmax"))

  print(vgg_16_model.summary())
  vgg_16_model.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['accuracy','Recall', 'Precision'])
  vgg_16_model.fit(train_x, train_y, epochs=30, validation_data=(val_x, val_y))
  vgg_16_model.evaluate(test_x, test_y)


In [5]:
digits = load_digits() # load the digit dataset

print('Example data: ')
print(digits.images[:5])
print('Example labels: ')
print(digits.target[:5])

x = digits.images
x = np.expand_dims(x, axis=-1) 
y_ = digits.target.reshape(-1, 1) # Convert data to a single column

n_outputs = len(np.unique(y_))
print('Number of outputs: ')
print(n_outputs)

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_) 


Example data: 
[[[ 0.  0.  5. 13.  9.  1.  0.  0.]
  [ 0.  0. 13. 15. 10. 15.  5.  0.]
  [ 0.  3. 15.  2.  0. 11.  8.  0.]
  [ 0.  4. 12.  0.  0.  8.  8.  0.]
  [ 0.  5.  8.  0.  0.  9.  8.  0.]
  [ 0.  4. 11.  0.  1. 12.  7.  0.]
  [ 0.  2. 14.  5. 10. 12.  0.  0.]
  [ 0.  0.  6. 13. 10.  0.  0.  0.]]

 [[ 0.  0.  0. 12. 13.  5.  0.  0.]
  [ 0.  0.  0. 11. 16.  9.  0.  0.]
  [ 0.  0.  3. 15. 16.  6.  0.  0.]
  [ 0.  7. 15. 16. 16.  2.  0.  0.]
  [ 0.  0.  1. 16. 16.  3.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  0. 11. 16. 10.  0.  0.]]

 [[ 0.  0.  0.  4. 15. 12.  0.  0.]
  [ 0.  0.  3. 16. 15. 14.  0.  0.]
  [ 0.  0.  8. 13.  8. 16.  0.  0.]
  [ 0.  0.  1.  6. 15. 11.  0.  0.]
  [ 0.  1.  8. 13. 15.  1.  0.  0.]
  [ 0.  9. 16. 16.  5.  0.  0.  0.]
  [ 0.  3. 13. 16. 16. 11.  5.  0.]
  [ 0.  0.  0.  3. 11. 16.  9.  0.]]

 [[ 0.  0.  7. 15. 13.  1.  0.  0.]
  [ 0.  8. 13.  6. 15.  4.  0.  0.]
  [ 0.  2.  1. 13. 13.  0.  0.  0.]
  [ 0. 

In [6]:
lenet_5_model('digits', x, y, n_outputs)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 8, 8, 6)           156       
                                                                 
 average_pooling2d (AverageP  (None, 4, 4, 6)          0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 4, 4, 16)          2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 2, 2, 16)         0         
 ePooling2D)                                                     
                                                                 
 flatten (Flatten)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 120)               7

In [7]:
vgg_16_model('digits', x, y, n_outputs)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 8, 8, 64)          640       
                                                                 
 conv2d_3 (Conv2D)           (None, 8, 8, 64)          36928     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 4, 4, 64)         0         
 )                                                               
                                                                 
 conv2d_4 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 conv2d_5 (Conv2D)           (None, 4, 4, 128)         147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 2, 2, 128)        0         
 2D)                                                  

In [8]:
olivetti = fetch_olivetti_faces() #load faces dataset

print('Example data: ')
print(olivetti.images[:5])
print('Example labels: ')
print(olivetti.target[:5])

x = olivetti.images
x = np.expand_dims(x, axis=-1) 
y_ = olivetti.target.reshape(-1, 1) # Convert data to a single column

n_outputs = len(np.unique(y_))
print('Number of outputs: ')
print(n_outputs)

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_) 


downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /root/scikit_learn_data
Example data: 
[[[0.30991736 0.3677686  0.41735536 ... 0.37190083 0.3305785  0.30578512]
  [0.3429752  0.40495867 0.43801653 ... 0.37190083 0.338843   0.3140496 ]
  [0.3429752  0.41735536 0.45041323 ... 0.38016528 0.338843   0.29752067]
  ...
  [0.21487603 0.20661157 0.2231405  ... 0.15289256 0.16528925 0.17355372]
  [0.20247933 0.2107438  0.2107438  ... 0.14876033 0.16115703 0.16528925]
  [0.20247933 0.20661157 0.20247933 ... 0.15289256 0.16115703 0.1570248 ]]

 [[0.45454547 0.47107437 0.5123967  ... 0.19008264 0.18595041 0.18595041]
  [0.446281   0.48347107 0.5206612  ... 0.21487603 0.2107438  0.2107438 ]
  [0.49586776 0.5165289  0.53305787 ... 0.20247933 0.20661157 0.20661157]
  ...
  [0.77272725 0.78099173 0.7933884  ... 0.1446281  0.1446281  0.1446281 ]
  [0.77272725 0.7768595  0.7892562  ... 0.13636364 0.13636364 0.13636364]
  [0.7644628  0.7892562  0.78099173 ... 0.15289256 

In [9]:
lenet_5_model('olivetti', x, y, n_outputs)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 64, 64, 6)         156       
                                                                 
 average_pooling2d_2 (Averag  (None, 32, 32, 6)        0         
 ePooling2D)                                                     
                                                                 
 conv2d_13 (Conv2D)          (None, 32, 32, 16)        2416      
                                                                 
 average_pooling2d_3 (Averag  (None, 16, 16, 16)       0         
 ePooling2D)                                                     
                                                                 
 flatten_2 (Flatten)         (None, 4096)              0         
                                                                 
 dense_6 (Dense)             (None, 120)              

In [10]:
vgg_16_model('olivetti', x, y, n_outputs)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_14 (Conv2D)          (None, 64, 64, 64)        640       
                                                                 
 conv2d_15 (Conv2D)          (None, 64, 64, 64)        36928     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 32, 32, 64)       0         
 2D)                                                             
                                                                 
 conv2d_16 (Conv2D)          (None, 32, 32, 128)       73856     
                                                                 
 conv2d_17 (Conv2D)          (None, 32, 32, 128)       147584    
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 16, 16, 128)      0         
 2D)                                                  

After training the two models on the two differents, we was able to achieve  an accaracy of over 90% on the test datasets using LetNet5 architecture, which is quite useful for such a simple network.
We can say that LetNet5 architecture has a better performance compared to the VGG16 architecture on both datasets

# 2.Fine tuning a pretrained model

In [28]:
#Loading datasets
digits = load_digits()
faces = fetch_olivetti_faces()

## Finetuning VGG16

In [40]:
def finetuning_vgg16(dataset, num_classes) : 
  if (dataset == 'digits') : 
    X = digits.images
    y = digits.target
  elif (dataset == 'faces') :
    X = faces.images
    y = faces.target

  #train_test_split
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  #Preprocessing dataset
  X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2], 1))
  y_train = to_categorical(y_train, num_classes = num_classes)

  x = tf.image.grayscale_to_rgb(tf.constant(X_train))
  x = tf.pad(x, ((0, 0), (12, 12), (12, 12), (0, 0)))

  #Preprocess input of VGG16
  x = keras.applications.vgg16.preprocess_input(tf.cast(x, tf.float32))

  model = keras.Sequential()
  core = keras.applications.VGG16(
    include_top=False,
    weights='imagenet',
    input_shape=x.shape[1:]
  )
  for layer in core.layers[:-2]:
    layer.trainable = False

  model.add(core)
  model.add(keras.layers.Flatten())
  model.add(keras.layers.Dense(num_classes, activation='softmax'))  

  model.compile(
    optimizer=keras.optimizers.Adam(),
    loss='categorical_crossentropy',
    metrics=['accuracy','Recall', 'Precision']
  )
  history = model.fit(x, y_train, validation_split=0.2, epochs=30)

  #evaluation
  X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], X_test.shape[2], 1))
  y_test = to_categorical(y_test, num_classes = num_classes)

  x = tf.image.grayscale_to_rgb(tf.constant(X_test))
  x = tf.pad(x, ((0, 0), (12, 12), (12, 12), (0, 0)))

  #Preprocess input of VGG16
  x = keras.applications.vgg16.preprocess_input(tf.cast(x, tf.float32))

  model.evaluate(x, y_test)



### Training and evaluation of VGG16 on digits dataset

In [41]:
finetuning_vgg16('digits', 10)

Epoch 1/30
36/36 [==============================] - 3s 45ms/step - loss: 7.1815 - accuracy: 0.2507 - recall: 0.2211 - precision: 0.2560 - val_loss: 1.6060 - val_accuracy: 0.5451 - val_recall: 0.3819 - val_precision: 0.5978
Epoch 2/30
36/36 [==============================] - 1s 33ms/step - loss: 1.2687 - accuracy: 0.5788 - recall: 0.4839 - precision: 0.6588 - val_loss: 0.8320 - val_accuracy: 0.7118 - val_recall: 0.6354 - val_precision: 0.8097
Epoch 3/30
36/36 [==============================] - 1s 29ms/step - loss: 0.8561 - accuracy: 0.7206 - recall: 0.6406 - precision: 0.8142 - val_loss: 0.9370 - val_accuracy: 0.7014 - val_recall: 0.6181 - val_precision: 0.7511
Epoch 4/30
36/36 [==============================] - 1s 29ms/step - loss: 0.8531 - accuracy: 0.7198 - recall: 0.6493 - precision: 0.7836 - val_loss: 0.6543 - val_accuracy: 0.7951 - val_recall: 0.7326 - val_precision: 0.8440
Epoch 5/30
36/36 [==============================] - 1s 29ms/step - loss: 0.6492 - accuracy: 0.7868 - recall:

### Training and evaluation of VGG16 on Faces dataset

In [42]:
finetuning_vgg16('faces', 40)

Epoch 1/30
8/8 [==============================] - 3s 205ms/step - loss: 5.2845 - accuracy: 0.0195 - recall: 0.0039 - precision: 0.0312 - val_loss: 4.1115 - val_accuracy: 0.0000e+00 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 2/30
8/8 [==============================] - 1s 92ms/step - loss: 3.8008 - accuracy: 0.0234 - recall: 0.0000e+00 - precision: 0.0000e+00 - val_loss: 3.6859 - val_accuracy: 0.0312 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 3/30
8/8 [==============================] - 1s 84ms/step - loss: 3.6891 - accuracy: 0.0273 - recall: 0.0000e+00 - precision: 0.0000e+00 - val_loss: 3.6901 - val_accuracy: 0.0156 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 4/30
8/8 [==============================] - 1s 84ms/step - loss: 3.6882 - accuracy: 0.0312 - recall: 0.0000e+00 - precision: 0.0000e+00 - val_loss: 3.6908 - val_accuracy: 0.0156 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 5/30
8/8 [==============================] - 1s 82

## Finetuning ResNet50v2

In [43]:
def finetuning_Resnet50v2(dataset, num_classes) : 
  if (dataset == 'digits') : 
    X = digits.images
    y = digits.target
  elif (dataset == 'faces') :
    X = faces.images
    y = faces.target

  #train_test_split
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  #Preprocessing dataset
  X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2], 1))
  y_train = to_categorical(y_train, num_classes = num_classes)

  x = tf.image.grayscale_to_rgb(tf.constant(X_train))
  x = tf.pad(x, ((0, 0), (12, 12), (12, 12), (0, 0)))

  #Preprocess input of ResNet50v2
  x = keras.applications.resnet_v2.preprocess_input(tf.cast(x, tf.float32))

  model = keras.Sequential()
  core = keras.applications.ResNet50V2(
    include_top=False,
    weights='imagenet',
    input_shape=x.shape[1:]
  )
  for layer in core.layers[:-2]:
    layer.trainable = False

  model.add(core)
  model.add(keras.layers.Flatten())
  model.add(keras.layers.Dense(num_classes, activation='softmax'))  

  model.compile(
    optimizer=keras.optimizers.Adam(),
    loss='categorical_crossentropy',
    metrics=['accuracy','Recall', 'Precision']
  )
  history = model.fit(x, y_train, validation_split=0.2, epochs=30)

  #evaluation
  X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], X_test.shape[2], 1))
  y_test = to_categorical(y_test, num_classes = num_classes)

  x = tf.image.grayscale_to_rgb(tf.constant(X_test))
  x = tf.pad(x, ((0, 0), (12, 12), (12, 12), (0, 0)))

  #Preprocess input of ResNet50v2
  x = keras.applications.resnet_v2.preprocess_input(tf.cast(x, tf.float32))

  model.evaluate(x, y_test)



### Training and evaluation of ResNet50v2 on digits dataset

In [44]:
finetuning_Resnet50v2('digits', 10)

Epoch 1/30
36/36 [==============================] - 10s 113ms/step - loss: 1.5214 - accuracy: 0.5457 - recall: 0.2802 - precision: 0.8070 - val_loss: 2.2577 - val_accuracy: 0.1424 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 2/30
36/36 [==============================] - 2s 45ms/step - loss: 0.8341 - accuracy: 0.8181 - recall: 0.5196 - precision: 0.9171 - val_loss: 2.2653 - val_accuracy: 0.1111 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 3/30
36/36 [==============================] - 2s 43ms/step - loss: 0.6671 - accuracy: 0.8660 - recall: 0.6162 - precision: 0.9340 - val_loss: 2.2704 - val_accuracy: 0.1458 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 4/30
36/36 [==============================] - 2s 45ms/step - loss: 0.5396 - accuracy: 0.9043 - recall: 0.6884 - precision: 0.9670 - val_loss: 2.2717 - val_accuracy: 0.1285 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 5/30
36/36 [==============================] - 1s 37ms/step - loss: 0

## Training and evaluation of ResNet50v2 on faces dataset

In [46]:
finetuning_Resnet50v2('faces', 40)

Epoch 1/30
8/8 [==============================] - 6s 265ms/step - loss: 4.2066 - accuracy: 0.0977 - recall: 0.0117 - precision: 1.0000 - val_loss: 4.0013 - val_accuracy: 0.0469 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 2/30
8/8 [==============================] - 1s 81ms/step - loss: 2.3416 - accuracy: 0.4219 - recall: 0.0898 - precision: 0.9200 - val_loss: 4.0144 - val_accuracy: 0.0000e+00 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 3/30
8/8 [==============================] - 1s 78ms/step - loss: 1.5104 - accuracy: 0.6367 - recall: 0.3281 - precision: 0.9333 - val_loss: 3.9154 - val_accuracy: 0.0469 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 4/30
8/8 [==============================] - 1s 77ms/step - loss: 1.0335 - accuracy: 0.7344 - recall: 0.4570 - precision: 0.9590 - val_loss: 3.8991 - val_accuracy: 0.0469 - val_recall: 0.0000e+00 - val_precision: 0.0000e+00
Epoch 5/30
8/8 [==============================] - 1s 76ms/step - loss: 0.7270 -

**Interpretation** :  According to the experiments using  VGG16 and Resnet50v2 on digits dataset and faces dataset and the results of the accuracy metric, we can say that Resnet50v2 has a better performance compared to the VGG16 on both datasets.

The best model is Resnet50v2 and its are characteristics are : 

* Optimizer : Adam

* Loss : categorical crossentropy

* last layer with softmax activation function





**Conclusion** : From the last lab and compared to the fully connected network, the Resnet50v2 pretrained model achieves better results on the faces dataset.